### PR TITLE
Update to 1.13

### PR DESCRIPTION
**Pull request by nfrickler**
This updates the plugin to be usable with Version 1.13:
 - Update repository list in POM to existing ones
 - Update bukkit version to 1.13
 - Change api version to 1.13
 - Update plugin channel name
 - Update naming of block
 - Use File instead of Stream for YamlConfiguration
 - Get rid of some deprecated stuff

Worked for me on a Spigot 1.13 server.

### CODE REVIEW

**Comment by OllieMartin** [comment]
Fantastic, I’d only changed the channel name in #669, couldn’t compile to see if there were any other issues. Will definitely be trying this ASAP.

Thank you :)

**Comment by minoneer** [comment]
Thanks for updating, was about to do the same when I found this 😀

**Comment by GothkittyGirl** [comment]
ok so how do i update the plugin i have or do i just redownload it?

**Comment by nfrickler** [comment]
@OllieMartin You're welcome :)

@GothkittyGirl To get this update you need to build the jar yourself from the provided source. For the sake of simplicity, you can also download the result here, if you want: https://www.dropbox.com/s/pge175unx6hp7cw/VanishNoPacket.jar?dl=0

**Comment by rlf** [comment]
Good job @nfrickler , was creating a PR of my own, but yours seemed better! :D

**Comment by mbax** [comment]
https://github.com/mbax/VanishNoPacket/commit/703455627dac0f7c4d75123a81811a519b5bab57

3.20.1 is compatible with Bukkit 1.7.10, the last Bukkit released before the project died. Coincidentally, I hear it runs on 1.13 versions of forks of the project that exist through ignoring DMCA takedown notices and other US copyright law.

I appreciate the PR <3

**Comment by mbax** [comment]
[3.20.1](https://dev.bukkit.org/projects/vanish/files/2597365) on DBO

**Pull request closed without merging**
