### PR TITLE
Bukkit to Spigot conversion and dependency update

### PR DESCRIPTION
**Pull request by digitalshadowhawk**
-updated to spigot 1.12 from bukkit 1.7.10
-removed spout support
-added shulker box support
-removed entity collision when vanished
-updated dependencies

### CODE REVIEW

**Comment by mbax** [comment]
Mix of tabs and spaces.

Also, I don't feel it appropriate to support a project (Spigot) that has violated US copyright law.

**Comment by digitalshadowhawk** [comment]
Spigot is not violating US copyright law. If they were putting Spigot (and the proprietary code that led to the DMCA) up for download, they would, in fact, be breaking the law, but at this point in time, the Spigot developers only provide a tool that allows the private modification and usage of gpl-licensed code and propietary code together, which is perfectly legal as long as the resulting products are not themselves published.

I realize you've had a rather... trying... history with the Spigot devs (md_5 in particular), but there are still those who would rather work with you on projects such as these rather than rant at you. I joined the Minecraft community around the time all this went down, perhaps slightly afterward, and wasn't aware of everything that was going on.

I will admit that the server I played on regularly was Bukkit and is now Spigot, so I'm a little biased, but from experience, I can say that the reason most people stuck with Spigot is because the Sponge project was still in its infancy at the time and simply lacked the resources that those on Bukkit/Spigot were used to and still had thanks to their compatibility.

I'm not saying that you should support Spigot builds indefinitely, or that I approve of what the Spigot devs did around the time of the DMCA, but that support during the time it takes to convince server owners to convert to the new Sponge servers would be greatly appreciated. After all, it can be a _little_ difficult to convince Minecraft players to try something new (we all know how the combat update went over)

As for the tab/spacing inconsistency, I'm still fresh into working with Maven projects instead of Gradle, and ran into several issues when trying to update it in one go and had to update it piece by piece. My editor doesn't like working with spaces, and I forgot to go back and fix it all, but it still works.

**Comment by mbax** [comment]
> Spigot is not violating US copyright law.

They ignored a DMCA takedown notice, and the exact CraftBukkit code that lead to the DMCA was still distributed by them (not in patch format) as of a year ago when I last checked. I don't bother to check that often. 

My avoidance of pulling this code isn't just about the DMCA takedown or the mess I dealt with personally, it's that I'm not going to get myself into legal complications. I'm aware of several plugin developers who spoke with lawyers, and the unanimous response was to not develop Bukkit plugins. 

You've written a lot of insightful commentary on the Minecraft community in the above comment that I'd love to respond to given the free time, but I don't have that right now. I appreciate the effort you put into the code, but I'm not going to pull this code into this repo. :(

**Comment by mbax** [comment]
Writing then deleting this in case you follow exclusively by email: Modified from "that time right now" to "that time today" to be more clear.

**Pull request closed without merging**
